# Introduction to NumPy

## What is NumPy?

NumPy, short for Numerical Python, is a powerful library in Python that is used for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in data analysis, machine learning, and scientific research due to its speed and functionality.

## Uses of NumPy

1. **Array Handling**: NumPy allows for the creation and manipulation of n-dimensional arrays (ndarray).
2. **Mathematical Operations**: It includes a vast range of mathematical operations (e.g., trigonometric, statistical, and algebraic functions) that can be performed on arrays.
3. **Linear Algebra**: NumPy provides tools for performing complex linear algebra operations.
4. **Random Number Generation**: It has utilities for generating random numbers and performing random sampling.
5. **Integration with Other Libraries**: NumPy is the foundation for many other scientific libraries like SciPy, Pandas, and Matplotlib.
6. **Performance**: NumPy is implemented in C, which makes it much faster for numerical operations compared to pure Python.

## Difference Between NumPy Array and List

### Type and Structure

- **NumPy Array (ndarray)**: A homogeneous, fixed-size array of numerical data. All elements must be of the same type.
- **Python List**: A heterogeneous, dynamically sized collection that can contain elements of different types.

### Performance

- **NumPy Array**: Optimized for numerical operations and can be much faster due to its implementation in C. It also supports vectorized operations, which allows element-wise operations to be applied without explicit loops.
- **Python List**: Slower for numerical operations as it requires iteration and type checking for each element.

### Memory Efficiency

- **NumPy Array**: More memory-efficient due to its homogeneous nature and contiguous memory allocation.
- **Python List**: Less memory-efficient because each element is a full Python object, including additional overhead for dynamic typing and memory management.

### Functionality

- **NumPy Array**: Provides a wide range of mathematical functions and capabilities, such as broadcasting, which allows operations on arrays of different shapes.
- **Python List**: Limited in terms of direct numerical and mathematical functionality, often requiring explicit loops and external functions.

### Dimensionality

- **NumPy Array**: Supports multi-dimensional arrays (e.g., 2D matrices, 3D tensors) which are essential for various numerical computations.
- **Python List**: Primarily supports one-dimensional lists, though nested lists can be used to approximate multi-dimensional structures, but with less efficiency and more complexity.

## Numpy array vs list :

1. A list can not directly handle mathemetical operation, while Array can.
2. An array consumes less memory than list.
3. Using an array is faster than list.
4. A list can store different data types, while you can't do that in array.
5. A list is easier to modify since a list store each element individually, it is easier to add and remove an element than array does.
6. In list one can have nested data with different size, while you can not do the same in array.

## Example Comparison

### Creating a NumPy Array

```python
import numpy as np

# Creating a 1D NumPy array
array = np.array([1, 2, 3, 4, 5])
print(array)


In [17]:
import numpy as np

In [18]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
n = 4

In [19]:
print(l1 + l2)
print(l1 * n)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([2])

print(type(c))

<class 'numpy.ndarray'>


In [21]:
# it performs direct mathemetical oprations.
print(a + b)
print(a * b)
print(a * c)

[5 7 9]
[ 4 10 18]
[2 4 6]


In [22]:
# numpy array doesn't support multiple data type.

x = np.array([1, 2, '3'])
y = np.array([4, 5.0, 6])

print(x)
print(y)

['1' '2' '3']
[4. 5. 6.]


In [24]:
# In list one can have nested data with different size, while you can not do the same in array.

l = [[1, 2], [3, 4, 5]]
print(l)

[[1, 2], [3, 4, 5]]


In [26]:
arr = np.array([[1, 2], [3, 4, 5]])
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [27]:
arr = np.array([[1, 2, 3], [3, 4, 5]])
print(arr)

[[1 2 3]
 [3 4 5]]


### Creation, Indexing, and Slicing of Numpy Arrays

In [29]:
# creating n dimentional array.

arr = np.array(
    [[1 ,2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
# slicing an array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [31]:
print(arr[:])
print(arr[:4])
print(arr[3:])
print(arr[2:9])
print(arr[::2])

[1 2 3 4 5 6 7 8 9 0]
[1 2 3 4]
[4 5 6 7 8 9 0]
[3 4 5 6 7 8 9]
[1 3 5 7 9]


In [33]:
# slicing in n dimentional array

arr = np.array(
    [[1 ,2, 3],
    [4, 5, 6]]
)

In [34]:
print(arr[0:2, 0:2])

[[1 2]
 [4 5]]


In [40]:
# for both it give 3 values.
print(arr[0:2, 0:3])

[[1 2 3]
 [4 5 6]]


In [41]:
# here we are slicing the list present in oth index of array.
print(arr[0, 1:3])

[2 3]


In [44]:
print(arr[1,2])

6


In [45]:
print(arr[2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [46]:
print(arr[0, 4])

IndexError: index 4 is out of bounds for axis 1 with size 3

In [47]:
print(arr[0, :100])

[1 2 3]


In [49]:
arr = np.array(
    [[1 ,2, 3, 5],
    [4, 5, 6, 9],
    [7, 8, 9, 0]]
)

print(arr)
print('data_type :', arr.dtype)
print('shape :', np.shape(arr))
print('size :', np.size(arr))
print('n-dimention :', np.ndim(arr))

[[1 2 3 5]
 [4 5 6 9]
 [7 8 9 0]]
data_type : int32
shape : (3, 4)
size : 12
n-dimention : 2


### Inspecting an Array

In [51]:
l = [[1,2,3,4],[5,6,7,8],[9,0,3,5]]

arr = np.array(l)
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 3 5]]


In [64]:
# rows, column
print('shape :', arr.shape)
print('shape :', np.shape(arr))

shape : (3, 4)
shape : (3, 4)


In [65]:
# number of nested value
print('length :', len(arr))

length : 3


In [66]:
# number of elements
print('size :', np.size(arr))

size : 12


In [67]:
# datatype of variable
print('type :', type(arr))

type : <class 'numpy.ndarray'>


In [68]:
# datatype of array
print('dtype :', arr.dtype)

dtype : int32


In [69]:
# convertion the data type

print(arr.astype(float))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [9. 0. 3. 5.]]


In [70]:
print(arr.astype(str))

[['1' '2' '3' '4']
 ['5' '6' '7' '8']
 ['9' '0' '3' '5']]


In [71]:
arr = np.array(
    [[1 ,2, 3, '5'],
    [4, 5, 6, 9],
    [7, 8, 9, 0]]
)

print(arr)

[['1' '2' '3' '5']
 ['4' '5' '6' '9']
 ['7' '8' '9' '0']]


In [72]:
print(arr.astype(int))

[[1 2 3 5]
 [4 5 6 9]
 [7 8 9 0]]


In [74]:
arr = np.array(
    [[1 ,2, 3.8, 5],
    [4, 5, 6, 9],
    [7, 8, 9, 0]]
)

print(arr)

[[1.  2.  3.8 5. ]
 [4.  5.  6.  9. ]
 [7.  8.  9.  0. ]]


In [73]:
arr = np.array(
    [[1 ,2, 3.8, '5'],
    [4, 5, 6, 9],
    [7, 8, 9, 0]]
)

print(arr)

[['1' '2' '3.8' '5']
 ['4' '5' '6' '9']
 ['7' '8' '9' '0']]


In [75]:
print(arr.astype(int))

[[1 2 3 5]
 [4 5 6 9]
 [7 8 9 0]]


In [76]:
print(arr.astype(float))

[[1.  2.  3.8 5. ]
 [4.  5.  6.  9. ]
 [7.  8.  9.  0. ]]


In [77]:
arr = np.array(
    [[1 ,2, 3.8, 'hello'],
    [4, 5, 6, 9],
    [7, 8, 9, 0]]
)

print(arr)

[['1' '2' '3.8' 'hello']
 ['4' '5' '6' '9']
 ['7' '8' '9' '0']]


In [78]:
print(arr.astype(int))

ValueError: invalid literal for int() with base 10: '3.8'

### Mathematical Operations and Functions on Arrays

In [87]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[2,5,8],[9,5,3]])
arr3 = np.array([2])

In [88]:
print(arr1 + arr2)
print('-'*50)
print(np.add(arr1, arr2))

[[ 3  7 11]
 [13 10  9]]
--------------------------------------------------
[[ 3  7 11]
 [13 10  9]]


In [89]:
print(arr1 - arr2)
print('-'*50)
print(np.subtract(arr1, arr2))

[[-1 -3 -5]
 [-5  0  3]]
--------------------------------------------------
[[-1 -3 -5]
 [-5  0  3]]


In [90]:
print(arr1 * arr2)
print('-'*50)
print(np.multiply(arr1, arr2))

[[ 2 10 24]
 [36 25 18]]
--------------------------------------------------
[[ 2 10 24]
 [36 25 18]]


In [91]:
print(arr1 / arr2)
print('-'*50)
print(np.divide(arr1, arr2))

[[0.5        0.4        0.375     ]
 [0.44444444 1.         2.        ]]
--------------------------------------------------
[[0.5        0.4        0.375     ]
 [0.44444444 1.         2.        ]]


In [93]:
print(arr1)
print('-'*50)
print(np.power(arr1, arr3))

[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[[ 1  4  9]
 [16 25 36]]


In [95]:
arr = np.array([4,16,64,81,100])

print(arr)
print('-'*50)
print(np.sqrt(arr))

[  4  16  64  81 100]
--------------------------------------------------
[ 2.  4.  8.  9. 10.]


### Combining and Splitting Arrays

In [4]:
# Concatenate
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate([arr1, arr2]))

[1 2 3 4 5 6]


In [5]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

print(np.concatenate([arr1, arr2]))

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [6]:
print(np.concatenate([arr1, arr2], axis = 0))

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [7]:
print(np.concatenate([arr1, arr2], axis = 1))

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [8]:
print(np.hstack([arr1, arr2])) # horizontal concatenation

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [9]:
print(np.vstack([arr1, arr2])) # vertical concatenation

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [15]:
# Split

arr = np.array([10, 20, 30, 40, 50, 60])

res = np.array_split(arr, 2)
print(res)

[array([10, 20, 30]), array([40, 50, 60])]


In [21]:
print(res[0])

[10 20 30]


In [16]:
print(np.array_split(arr, 3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [17]:
print(np.array_split(arr, 4))

[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [18]:
print(np.array_split(arr, 5))

[array([10, 20]), array([30]), array([40]), array([50]), array([60])]


In [19]:
print(np.array_split(arr, 6))

[array([10]), array([20]), array([30]), array([40]), array([50]), array([60])]


In [20]:
print(np.array_split(arr, 7))

[array([10]), array([20]), array([30]), array([40]), array([50]), array([60]), array([], dtype=int32)]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

res = np.array_split(arr, 3)
print(res)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [23]:
print(res[2])

[]


In [25]:
print(np.array_split(arr, 2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [27]:
print(np.array_split(arr, 4)[3])

[]


### Adding and Removing Elements in the Arrays

In [29]:
# append

arr = np.array([1, 2, 3, 4])

print(np.append(arr, 5))
print(arr)

[1 2 3 4 5]
[1 2 3 4]


In [30]:
arr = np.append(arr, [6, 7])
print(arr)

[1 2 3 4 6 7]


In [34]:
arr = np.array([[1,2,3], [4,5,6]])

print(np.append(arr, 7)) # converts the array in one dimension and then append the value.

[1 2 3 4 5 6 7]


In [35]:
print(np.append(arr, [8, 9]))

[1 2 3 4 5 6 8 9]


In [40]:
print(np.append(arr, [7, 8, 9]))

[1 2 3 4 5 6 7 8 9]


In [41]:
# insert

arr = arr = np.array([1, 2, 3, 4])

print(np.insert(arr, 1, 10))

[ 1 10  2  3  4]


In [42]:
print(np.insert(arr, 2, [10, 20]))

[ 1  2 10 20  3  4]


In [45]:
print(np.insert(arr, 1, 5, axis = 0))

[1 5 2 3 4]


In [46]:
print(np.insert(arr, 1, 5, axis = 1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [48]:
arr = np.array([[1,2,3], [4,5,6]])

print(np.insert(arr, 1, 5)) # if we didn't provide axis, it converts array into one dimention then inserts the value.

[1 5 2 3 4 5 6]


In [49]:
print(np.insert(arr, 2, [30, 40]))

[ 1  2 30 40  3  4  5  6]


In [50]:
print(np.insert(arr, 2, [30, 40], axis = 0))

ValueError: could not broadcast input array from shape (1,2) into shape (1,3)

In [51]:
print(np.insert(arr, 2, [30], axis = 0))

[[ 1  2  3]
 [ 4  5  6]
 [30 30 30]]


In [52]:
print(np.insert(arr, 2, [30], axis = 1))

[[ 1  2 30  3]
 [ 4  5 30  6]]


In [53]:
print(np.insert(arr, 2, [30, 40, 60], axis = 0))

[[ 1  2  3]
 [ 4  5  6]
 [30 40 60]]


In [55]:
print(np.insert(arr, 2, [30, 40, 60], axis = 1))

ValueError: could not broadcast input array from shape (3,1) into shape (2,1)

In [56]:
print(np.insert(arr, 2, [30, 40], axis = 1))

[[ 1  2 30  3]
 [ 4  5 40  6]]


In [57]:
# delete

arr = np.array([1, 2, 3, 4])

print(np.delete(arr, 1))
print(arr)

[1 3 4]
[1 2 3 4]


In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.delete(arr, 2)) # converts array in one dimention the deletes the element.
print(arr)

[1 2 4 5 6]
[[1 2 3]
 [4 5 6]]


In [60]:
print(np.delete(arr, 0, axis = 0))

[[4 5 6]]


In [61]:
print(np.delete(arr, 0, axis = 1))

[[2 3]
 [5 6]]


### Search, Sort, and Filter Arrays

In [63]:
# Sort

arr = np.array([1, 5 , 9, 6, 0, 3])

print(np.sort(arr))
print(arr)

[0 1 3 5 6 9]
[1 5 9 6 0 3]


In [65]:
arr = np.array([[1, 0, 3], [4, 7, 6]])

print(np.sort(arr))

[[0 1 3]
 [4 6 7]]


In [67]:
print(np.sort(arr)[::-1])

[[4 6 7]
 [0 1 3]]


In [68]:
# search

arr = np.array([1, 2, 8, 9, 5])

s = np.where(arr == 2)
print(s)

(array([1], dtype=int64),)


In [69]:
s = np.where(arr%2 == 0)
print(s)

(array([1, 2], dtype=int64),)


In [71]:
arr = np.array([1, 2, 3, 4, 5])

ss = np.searchsorted(arr, 2)
print(ss)

1


In [72]:
ss = np.searchsorted(arr, 5)
print(ss)

4


In [78]:
arr = np.array([1, 5, 2, 4, 3, 8])

print(np.searchsorted(arr, 1))

0


In [79]:
print(np.searchsorted(arr, 2))

1


In [80]:
print(np.searchsorted(arr, 8))

5


In [86]:
arr = np.array([[1, 3, 4], [2, 6, 5]])

s = np.where(arr[0] == 2)

print(s)

(array([], dtype=int64),)


In [88]:
s = np.where(arr == 2)
print(s)

(array([1], dtype=int64), array([0], dtype=int64))


In [82]:
# filter

arr = np.array([20,30,40,50])

filter_array = [True, False, True, False]

new_array = arr[filter_array]

print(new_array)

[20 40]


In [83]:
fa = arr > 35

print(arr[fa])

[40 50]


In [85]:
fa = arr % 3 == 0

print(arr[fa])

[30]


In [90]:
arr = np.array([[10, 30, 20], [40, 50, 60]])

fa = (arr >= 30)

print(arr[fa])

[30 40 50 60]


In [91]:
fa = (arr%3 == 0)

print(arr[fa])

[30 60]


### Aggregating Functions in Arrays

In [92]:
arr = np.array([17, 29, 35, 40, 53])

print(np.sum(arr))

174


In [93]:
print(np.min(arr))

17


In [94]:
print(np.max(arr))

53


In [95]:
print(np.size(arr))

5


In [97]:
print(np.mean(arr)) # it gives the avrage value

34.8


In [98]:
print(np.cumsum(arr)) # cumulative sum --> it adds all the previous index value along with current index and gives the result.

[ 17  46  81 121 174]


In [99]:
print(np.cumprod(arr))

[      17      493    17255   690200 36580600]


In [100]:
a = [100, 250, 50, 30]
b = [3, 4, 8, 6]

price = np.array(a)
quantity = np.array(b)

c = np.cumprod([price, quantity])

print(c)

[       100      25000    1250000   37500000  112500000  450000000
 -694967296  125163520]


In [102]:
c = np.cumprod([price, quantity], axis = 1)

print(c)

[[     100    25000  1250000 37500000]
 [       3       12       96      576]]


In [103]:
c = np.cumprod([price, quantity], axis = 0)

print(c)

[[ 100  250   50   30]
 [ 300 1000  400  180]]


In [104]:
print(c[1])

[ 300 1000  400  180]


In [106]:
total_price = c[1].sum()

print(total_price)

1880


### Statistical Functions in Arrays

In [111]:
import statistics as stats
baked_food = np.array([100, 289, 230, 180, 150, 230, 100, 180])

print(np.mean(baked_food)) # sum of all val / number of val
print(np.median(baked_food)) # central val after sorting (even - it give exact center val after some calculation).
print(stats.mode(baked_food)) # the first occurence val repeated more times.

182.375
180.0
100


In [113]:
# Standard deviation is a measure of the amount of variation or dispersion in a set of values. sd = sqrt(variance)
print(np.std(baked_food))

61.78174791149891


In [114]:
print(np.var(baked_food))

3816.984375


In [115]:
# -1 represents inversly propotional relationship
# 1 represents propotional relationship
# 0 means no relationship

sales = [100, 200, 350, 120, 200]
price = [10, 30, 26, 50, 34]

print(np.corrcoef([sales, price]))

[[ 1.         -0.03523714]
 [-0.03523714  1.        ]]
